# Generated by Django 5.0.2 on 2026-02-02 21:47

from django.db import migrations

def copy_units(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    UnitOfMeasure = apps.get_model('core', 'UnitOfMeasure')
    
    for product in Product.objects.all():
        if not product.unit:
            continue
            
        abbr = product.unit.strip().lower()
        if not abbr:
            continue
            
        # Try to find existing unit, or create a temporary one if unknown
        unit_obj, created = UnitOfMeasure.objects.get_or_create(
            abbreviation=abbr,
            defaults={'name': abbr.capitalize()}
        )
        
        product.unit_fk = unit_obj
        product.save()

def reverse_copy_units(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.unit_fk:
            product.unit = product.unit_fk.abbreviation
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_unit_fk'),
        ('core', '0003_populate_units'),
    ]

    operations = [
        migrations.RunPython(copy_units, reverse_copy_units),
    ]
