# Generated by Django 5.0.2 on 2026-02-03 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_copy_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Embalagem',
                'verbose_name_plural': 'Embalagens',
                'db_table': 'packagings',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Tipo de embalagem do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.packaging', verbose_name='Embalagem'),
        ),
    ]
