# Generated by Django 5.0.2 on 2026-02-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_distributor_distributor_type'),
        ('products', '0005_packaging_product_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Matriz proprietária deste produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='distributors.distributor', verbose_name='Matriz'),
        ),
    ]
