# Generated by Django 5.0.2 on 2026-02-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_distributor'),
    ]

    operations = [
        # Original operations removed as part of Establishment cleanup
    ]
