# Generated by Django 5.0.2 on 2026-02-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_distributor_distributor_type'),
        ('products', '0007_alter_productstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='distributors.distributor', verbose_name='Distribuidor'),
        ),
    ]
