# Generated by Django 5.0.2 on 2026-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_distributor_distributor_type'),
        ('products', '0009_productstock_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='batch',
            field=models.CharField(default='S/L', max_length=50, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'distributor', 'batch'), name='unique_product_distributor_batch'),
        ),
    ]
