# Generated by Django 5.0.2 on 2026-02-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_alter_distributor_code_alter_distributor_state'),
        ('products', '0010_remove_productstock_unique_product_establishment_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='productstock',
        #     name='establishment',
        # ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='distributors.distributor', verbose_name='Distribuidor'),
            preserve_default=False,
        ),
    ]
