# Generated by Django 5.0.2 on 2026-02-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_distributor_tipo_unidade_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='distributors.distributor', verbose_name='Filial de Destino'),
        ),
        migrations.AlterField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='distributors.distributor', verbose_name='CD de Origem (Matriz)'),
        ),
    ]
