# Generated by Django 5.0.2 on 2026-02-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_target_distributor_alter_order_distributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='establishment',
        ),
    ]
