# Generated by Django 5.0.2 on 2026-02-12 14:25

import apps.orders.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_target_distributor_alter_order_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_condition',
            field=models.CharField(choices=[('vista', 'À Vista'), ('prazo', 'À Prazo'), ('consignado', 'Consignado'), ('doacao', 'Doação')], default='vista', max_length=20, verbose_name='Condição de Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('total', 'Total'), ('isento', 'Isento')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('entregue', 'Entregue')], default='pendente', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AccountSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_reported', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Informado')),
                ('receipt_file', models.FileField(upload_to=apps.orders.models.settlement_file_path, verbose_name='Comprovante')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Prestação de Conta',
                'verbose_name_plural': 'Prestações de Contas',
                'ordering': ['-created_at'],
            },
        ),
    ]
