# Generated by Django 5.0.2 on 2026-02-12 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_condition_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettlement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa'),
        ),
        migrations.AddField(
            model_name='accountsettlement',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_settlements', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
