# Generated by Django 5.0.2 on 2026-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_accountsettlement_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo (Soft Delete)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo (Soft Delete)'),
        ),
    ]
