# Generated by Django 5.0.2 on 2026-02-01 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('estorno', 'Estorno')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('previous_stock', models.IntegerField(verbose_name='Estoque Anterior')),
                ('new_stock', models.IntegerField(verbose_name='Novo Estoque')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('reference_id', models.UUIDField(blank=True, help_text='ID do pedido ou outra referência', null=True, verbose_name='ID de Referência')),
                ('reference_type', models.CharField(blank=True, help_text='order, transfer, adjustment, etc.', max_length=50, null=True, verbose_name='Tipo de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
