# Generated by Django 5.0.2 on 2026-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada Manual'), ('exit', 'Saída Manual'), ('adjustment_plus', 'Ajuste (Adicionar)'), ('adjustment_minus', 'Ajuste (Subtrair)'), ('reversal_in', 'Estorno de Entrada'), ('reversal_out', 'Estorno de Saída')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
    ]
