# Generated by Django 5.0.2 on 2026-02-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_distributor_distributor_type'),
        ('stock', '0002_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='establishment',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='distributors.distributor', verbose_name='Distribuidor'),
        ),
    ]
