# Generated by Django 5.0.2 on 2026-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockmovement_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
