# Generated by Django 5.0.2 on 2026-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockmovement_batch_stockmovement_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada Manual'), ('exit', 'Saída Manual'), ('adjustment_plus', 'Ajuste (Adicionar)'), ('adjustment_minus', 'Ajuste (Subtrair)'), ('reversal_in', 'Estorno de Entrada'), ('reversal_out', 'Estorno de Saída'), ('transfer_out', 'Saída por Transferência'), ('transfer_in', 'Entrada por Transferência')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
    ]
