# Generated by Django 5.0.2 on 2026-02-01 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Quilograma, Unidade, Metro', max_length=50, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(help_text='Ex: kg, un, m', max_length=10, unique=True, verbose_name='Sigla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'units_of_measure',
                'ordering': ['name'],
            },
        ),
    ]
