# Generated by Django 5.0.2 on 2026-02-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Chave da Sequência')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Valor Atual')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequência',
                'verbose_name_plural': 'Sequências',
                'db_table': 'sequences',
            },
        ),
    ]
