# Generated by Django 5.0.2 on 2026-02-02 21:45

from django.db import migrations

def populate_units(apps, schema_editor):
    UnitOfMeasure = apps.get_model('core', 'UnitOfMeasure')
    
    # 1. Normalize existing 'KG' to 'kg' to avoid unique constraint error on name 'Quilograma'
    # if we try to insert 'kg'/'Quilograma' while 'KG'/'Quilograma' exists.
    UnitOfMeasure.objects.filter(abbreviation='KG').update(abbreviation='kg')
    
    units = [
        {'abbreviation': 'un', 'name': 'Unidade'},
        {'abbreviation': 'kg', 'name': 'Quilograma'},
        {'abbreviation': 'l', 'name': 'Litro'},
        {'abbreviation': 'cx', 'name': 'Caixa'},
        {'abbreviation': 'm', 'name': 'Metro'},
    ]
    
    for unit_data in units:
        # 2. Update or create based on abbreviation
        # If 'kg' exists (from update above or previous run), name is ensured.
        # If 'un' doesn't exist, it is created.
        UnitOfMeasure.objects.update_or_create(
            abbreviation=unit_data['abbreviation'],
            defaults={'name': unit_data['name']}
        )

def reverse_populate_units(apps, schema_editor):
    # No safe reverse possible without losing data, keeping it mostly empty or strict
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequence'),
    ]

    operations = [
        migrations.RunPython(populate_units, reverse_populate_units),
    ]
