# Generated by Django 5.0.2 on 2026-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
