# Generated by Django 5.0.2 on 2026-02-01 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='INSERT, UPDATE, DELETE', max_length=20, verbose_name='Ação')),
                ('table_name', models.CharField(max_length=100, verbose_name='Tabela')),
                ('record_id', models.UUIDField(blank=True, null=True, verbose_name='ID do Registro')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Dados Antigos')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['table_name'], name='audit_logs_table_n_1d2102_idx')],
            },
        ),
    ]
