# Generated by Django 5.0.2 on 2026-02-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='distributor_type',
            field=models.CharField(choices=[('headquarters', 'Matriz'), ('branch', 'Filial')], default='branch', help_text='Matriz tem permissões especiais no sistema', max_length=20, verbose_name='Tipo'),
        ),
    ]
