# Generated by Django 5.0.2 on 2026-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_distributor_distributor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='tipo_unidade',
            field=models.CharField(choices=[('MATRIZ', 'Matriz'), ('FILIAL', 'Filial')], default='FILIAL', help_text='Define se é Matriz ou Filial', max_length=10, verbose_name='Tipo de Unidade'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='distributor_type',
            field=models.CharField(choices=[('headquarters', 'Matriz'), ('branch', 'Filial')], default='branch', help_text='Mantido para compatibilidade', max_length=20, verbose_name='Tipo (Antigo)'),
        ),
    ]
