# Generated by Django 5.0.2 on 2026-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_alter_distributor_code_alter_distributor_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['name'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='distributor',
            name='tipo_unidade',
            field=models.CharField(choices=[('MATRIZ', 'Matriz / Fornecedor'), ('FILIAL', 'Filial / Comprador')], default='FILIAL', help_text='Define se é Matriz ou Filial', max_length=10, verbose_name='Tipo de Unidade'),
        ),
    ]
