# Generated by Django 5.0.2 on 2026-02-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Distribuidor ao qual o usuário pertence. Obrigatório para usuários não administradores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='distributors.distributor', verbose_name='Distribuidor'),
        ),
    ]
